---
name: reviewdog

on: [pull_request]
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: yamllint
        uses: reviewdog/action-yamllint@6803b0dc8f295034a6156b924814053acb2e6f5a
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.
          yamllint_flags: ".github/"
